In [6]:
import pandas as pd
import sqlite3

In [7]:
df_csv = pd.read_csv("C:/Users/bathr/Desktop/Cybrom_Class_Data/Machine_Learning/data/data.csv")
df_csv.head()

   id     name  age      city
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   35     Paris

In [8]:
df_excel = pd.read_excel('C:/Users/bathr/Desktop/Cybrom_Class_Data/Machine_Learning/data/data.xlsx',sheet_name=0)
df_excel.head()

   id     name  age      city
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   35     Paris

In [9]:
df_json = pd.read_json('C:/Users/bathr/Desktop/Cybrom_Class_Data/Machine_Learning/data/data.json')
df_json.head()

   id     name  age      city
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   35     Paris

In [10]:
conn = sqlite3.connect('C:/Users/bathr/Desktop/Cybrom_Class_Data/Machine_Learning/data/example.db')
df_sql = pd.read_sql_query('SELECT * FROM my_table', conn)
df_sql.head()

   id     name  age      city
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   35     Paris