In [1]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer

In [2]:
data = {
    "id" : [1,2,3,4,5,6],
    'age' : [25,np.nan, 30, 68, np.nan, 23],
    'salary':[50000,60000,np.nan,80000,90000,np.nan],
    'city' : ['New York', 'London',np.nan, 'Paris','London',np.nan ]
}

df = pd.DataFrame(data)

In [4]:
display(df)

   id   age   salary      city
0   1  25.0  50000.0  New York
1   2   NaN  60000.0    London
2   3  30.0      NaN       NaN
3   4  68.0  80000.0     Paris
4   5   NaN  90000.0    London
5   6  23.0      NaN       NaN

In [6]:
mean_imputer = SimpleImputer(strategy = 'mean')
df_mean = df.copy()

df_mean[['age', 'salary']] = mean_imputer.fit_transform(df_mean[['age', 'salary']])

print('\n Imputed Mean Data')

display(df_mean)

 Imputed Mean Data

   id   age   salary      city
0   1  25.0  50000.0  New York
1   2  36.5  60000.0    London
2   3  30.0  70000.0       NaN
3   4  68.0  80000.0     Paris
4   5  36.5  90000.0    London
5   6  23.0  70000.0       NaN

In [8]:
median_imputer = SimpleImputer(strategy= 'median')

df_median = df.copy()

df_median[['age', 'salary']] = median_imputer.fit_transform(df_median[['age', 'salary']])
print("\n Imputed Median Data")
display(df_median)

 Imputed Median Data

   id   age   salary      city
0   1  25.0  50000.0  New York
1   2  27.5  60000.0    London
2   3  30.0  70000.0       NaN
3   4  68.0  80000.0     Paris
4   5  27.5  90000.0    London
5   6  23.0  70000.0       NaN

In [10]:
mode_imputer = SimpleImputer(strategy = 'most_frequent')
df_data = df.copy()

df_data[['city']] = mode_imputer.fit_transform(df_data[['city']])
print("\n Imputed Mode Data")
display(df_data)

 Imputed Mode Data

   id   age   salary      city
0   1  25.0  50000.0  New York
1   2   NaN  60000.0    London
2   3  30.0      NaN    London
3   4  68.0  80000.0     Paris
4   5   NaN  90000.0    London
5   6  23.0      NaN    London

In [12]:
df_random = df.copy()

def random_impute(series):
    filled = series.dropna().tolist()
    return series.apply(lambda x: random.choice(filled) if pd.isnull(x) else x)

for col in ['age', 'city', 'salary']:
    df_random[col] = random_impute(df_random[col])

print("\n Random Imputed Data")
display(df_random)
display(df)

 Random Imputed Data

   id   age   salary      city
0   1  25.0  50000.0  New York
1   2  25.0  60000.0    London
2   3  30.0  60000.0    London
3   4  68.0  80000.0     Paris
4   5  23.0  90000.0    London
5   6  23.0  50000.0    London

   id   age   salary      city
0   1  25.0  50000.0  New York
1   2   NaN  60000.0    London
2   3  30.0      NaN       NaN
3   4  68.0  80000.0     Paris
4   5   NaN  90000.0    London
5   6  23.0      NaN       NaN