In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.DataFrame({
    'Age':[10,22,30,45,60,80,25,35,50,70],
    'Salary':[20000,25000,40000,60000,120000,100000,30000,50000,80000,150000],
    'Purchased':[0,0,0,1,1,1,0,1,1,1]
    })

print("Original Data:")
display(df)

Original Data:

   Age  Salary  Purchased
0   10   20000          0
1   22   25000          0
2   30   40000          0
3   45   60000          1
4   60  120000          1
5   80  100000          1
6   25   30000          0
7   35   50000          1
8   50   80000          1
9   70  150000          1

In [3]:
X = df[['Age', 'Salary']]
y = df['Purchased']

In [4]:
display(X)

   Age  Salary
0   10   20000
1   22   25000
2   30   40000
3   45   60000
4   60  120000
5   80  100000
6   25   30000
7   35   50000
8   50   80000
9   70  150000

In [5]:
display(y)

0    0
1    0
2    0
3    1
4    1
5    1
6    0
7    1
8    1
9    1
Name: Purchased, dtype: int64

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = .2,random_state = 42)

In [7]:
display(X_train)
print(X_train.shape)

   Age  Salary
5   80  100000
0   10   20000
7   35   50000
2   30   40000
9   70  150000
4   60  120000
3   45   60000
6   25   30000

(8, 2)

In [8]:
display(y_train)
print(y_train.shape)

5    1
0    0
7    1
2    0
9    1
4    1
3    1
6    0
Name: Purchased, dtype: int64

(8,)

In [9]:
display(X_test)
print(X_test.shape)

   Age  Salary
8   50   80000
1   22   25000

(2, 2)

In [10]:
display(y_test)
print(y_test.shape)

8    1
1    0
Name: Purchased, dtype: int64

(2,)